#ifndef NSDP_PROPERTIES_H
#define NSDP_PROPERTIES_H

#define NSDP_PROPERTY_NONE			0x0000
#define NSDP_PROPERTY_MODEL			0x0001
#define NSDP_PROPERTY_HOSTNAME			0x0003
#define NSDP_PROPERTY_MAC			0x0004
#define NSDP_PROPERTY_IP			0x0006
#define NSDP_PROPERTY_NETMASK			0x0007
#define NSDP_PROPERTY_GATEWAY			0x0008
#define NSDP_PROPERTY_PASSWORD			0x000A
#define NSDP_PROPERTY_DHCP			0x000B
#define NSDP_PROPERTY_FIRMWARE_VERSION		0x000D
#define NSDP_PROPERTY_PORT_STATUS		0x0C00
#define NSDP_PROPERTY_PORT_STATISTICS		0x1000
#define NSDP_PROPERTY_PORT_COUNT		0x6000
#define NSDP_PROPERTY_TERMINATOR		0xFFFF

#endif /* NSDP_PROPERTIES_H */
